// Cookies Name
export const USER_TOKEN_NAME = '_uuid';
export type USER_TOKEN_TYPE = typeof USER_TOKEN_NAME;

// Modal Views
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export type DELETE_PRODUCT_TYPE = typeof DELETE_PRODUCT;
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE';
export type DELETE_ATTRIBUTE_TYPE = typeof DELETE_ATTRIBUTE;
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export type DELETE_SUPPLIER_TYPE = typeof DELETE_SUPPLIER;
export const DELETE_ORDER = 'DELETE_ORDER';
export type DELETE_ORDER_TYPE = typeof DELETE_ORDER;
export const DELETE_COUPON = 'DELETE_COUPON';
export type DELETE_COUPON_TYPE = typeof DELETE_COUPON;
export const DELETE_SHIPPING = 'DELETE_SHIPPING';
export type DELETE_SHIPPING_TYPE = typeof DELETE_SHIPPING;
export const DELETE_DELIVERY_TIME = 'DELETE_DELIVERY_TIME';
export type DELETE_DELIVERY_TIME_TYPE = typeof DELETE_DELIVERY_TIME;
export const DELETE_ORDER_STATUS = 'DELETE_ORDER_STATUS';
export type DELETE_ORDER_STATUS_TYPE = typeof DELETE_ORDER_STATUS;
export const DELETE_TAG = 'DELETE_TAG';
export type DELETE_TAG_TYPE = typeof DELETE_TAG;
export const BAN_CUSTOMER = 'BAN_CUSTOMER';
export type BAN_CUSTOMER_TYPE = typeof BAN_CUSTOMER;
export const BAN_USER = 'BAN_USER';
export type BAN_USER_TYPE = typeof BAN_USER;
export const DELETE_USER = 'DELETE_USER';
export type DELETE_USER_TYPE = typeof DELETE_USER;
export const DELETE_PHOTO = 'DELETE_PHOTO';
export type DELETE_PHOTO_TYPE = typeof DELETE_PHOTO;
export const DELETE_SLIDER = 'DELETE_SLIDER';
export type DELETE_SLIDER_TYPE = typeof DELETE_SLIDER;
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';
export type DELETE_MANUFACTURER_TYPE = typeof DELETE_MANUFACTURER;
export const IMAGE_MODAL = 'IMAGE_MODAL';
export type IMAGE_MODAL_TYPE = typeof IMAGE_MODAL;
export const MEDIA_ITEM_MODAL = 'MEDIA_ITEM_MODAL';
export type MEDIA_ITEM_MODAL_TYPE = typeof MEDIA_ITEM_MODAL;
export const PRODUCT_MODAL = 'PRODUCT_MODAL';
export type PRODUCT_MODAL_TYPE = typeof PRODUCT_MODAL;

export const RELATED_PRODUCTS = 'RELATED_PRODUCTS';
export const UPSELL_PRODUCTS = 'UPSELL_PRODUCTS';
export const CROSS_SELL_PRODUCTS = 'CROSS_SELL_PRODUCTS';
