import { ACTION_PRIVILEGES, RESOURCES } from '@ts-types/enums';

export const resourceDefaultData = [
  {
    resource: RESOURCES.USER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.CATEGORY,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.PRODUCT,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.TAG,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.TAX,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.SUPPLIER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ATTRIBUTE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.CUSTOMER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.COUPON,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.SHIPPING,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ORDER_STATUS,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ORDER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ROLE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.SLIDERS,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.THEME,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.MARKETPLACE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE_SETTINGS,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.PAGES,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.MEDIA,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.MANUFACTURER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE_LANGUAGE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  }
  // {
  //   resource: RESOURCES.STORE_BUILDER,
  //   [ACTION_PRIVILEGES.WRITE]: false,
  //   [ACTION_PRIVILEGES.READ]: false,
  //   [ACTION_PRIVILEGES.UPDATE]: false,
  //   [ACTION_PRIVILEGES.DELETE]: false
  // }
];
