import { ACTION_PRIVILEGES, RESOURCES } from '@ts-types/enums';

export const resourceDefaultData = [
  {
    resource: RESOURCES.USER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.CATEGORY,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.PRODUCT,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.TAG,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.TAX,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.SUPPLIER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ATTRIBUTE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.CUSTOMER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.COUPON,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.SHIPPING,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ORDER_STATUS,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ORDER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.ROLE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.THEME,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.MARKETPLACE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE_SETTINGS,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.MEDIA,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.BRAND,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE_LANGUAGE,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.STORE_BUILDER,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  },
  {
    resource: RESOURCES.PAYMENT,
    [ACTION_PRIVILEGES.WRITE]: false,
    [ACTION_PRIVILEGES.READ]: false,
    [ACTION_PRIVILEGES.UPDATE]: false,
    [ACTION_PRIVILEGES.DELETE]: false
  }
];

export const resourcesNameMapper = {
  [RESOURCES.USER]: 'User',
  [RESOURCES.CATEGORY]: 'Category',
  [RESOURCES.PRODUCT]: 'Product',
  [RESOURCES.TAG]: 'Tag',
  [RESOURCES.TAX]: 'Tax',
  [RESOURCES.SUPPLIER]: 'Supplier',
  [RESOURCES.ATTRIBUTE]: 'Attribute',
  [RESOURCES.CUSTOMER]: 'Customer',
  [RESOURCES.COUPON]: 'Coupon',
  [RESOURCES.SHIPPING]: 'Shipping',
  [RESOURCES.ORDER_STATUS]: 'Order Status',
  [RESOURCES.ORDER]: 'Order',
  [RESOURCES.ROLE]: 'User Role',
  [RESOURCES.THEME]: 'Theme',
  [RESOURCES.MARKETPLACE]: 'MarketPlace',
  [RESOURCES.STORE_SETTINGS]: 'Store Settings',
  [RESOURCES.MEDIA]: 'Media',
  [RESOURCES.BRAND]: 'Brand',
  [RESOURCES.STORE_LANGUAGE]: 'Store Language',
  [RESOURCES.STORE_BUILDER]: 'Store Builder',
  [RESOURCES.PAYMENT]: 'Payment'
};
